version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: tblog
    environment:
        - JEKYLL_ENV=docker
    # force_polling makes the linux box watch for any changes to files, then it will regenerate
    # livereload gets the browser to automatically refresh when changes happen to files
    command: bundle exec jekyll serve -H 0.0.0.0 -t --drafts
    ports:
        - 4000:4000
        - 35729:35729
    volumes:
        - ./:/srv/jekyll
