version: "3.5"

services:
  jekyll:
    image: jekyll/builder
    environment:
      - JEKYLL_ENV
    ports:
      - 4000:4000
    container_name: jekyll
    volumes:
      - ..:/srv/jekyll
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve -H 0.0.0.0 -t --config ./_config.dev.yml
